name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 13
      uses: actions/setup-java@v4
      with:
        java-version: '13'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd android_YOLOV5_NCNN && chmod +x gradlew
      
    - name: Build with Gradle
      run: cd android_YOLOV5_NCNN && ./gradlew build
